const ROLES = {
  CUSTOMER: 'CUSTOMER',
  ADMIN: 'ADMIN',
};

const AUTH_COOKIE_NAME = 'access_token';

const CUSTOMIZATION_FIELD_TYPES = {
  TEXT: 'TEXT',
  IMAGE: 'IMAGE',
  NUMBER: 'NUMBER',
  SELECT: 'SELECT',
  TEXTAREA: 'TEXTAREA',
};

const ADDRESS_TYPES = {
  HOME: 'HOME',
  WORK: 'WORK',
  OTHER: 'OTHER',
};

const DISCOUNT_TYPES = {
  PERCENTAGE: 'PERCENTAGE',
  FLAT: 'FLAT',
};

const ORDER_STATUS = {
  PLACED: 'PLACED',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  PROCESSING: 'PROCESSING',
  CUSTOMIZATION: 'CUSTOMIZATION',
  READY_TO_SHIP: 'READY_TO_SHIP',
  SHIPPED: 'SHIPPED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
  FAILED: 'FAILED',
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  AUTHORIZED: 'AUTHORIZED',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

const DELIVERY_TYPES = {
  STANDARD: 'STANDARD',
  SAME_DAY: 'SAME_DAY',
  EXPRESS: 'EXPRESS',
  SCHEDULED: 'SCHEDULED',
};

const PAYMENT_PROVIDERS = {
  RAZORPAY: 'RAZORPAY',
};

module.exports = {
  ROLES,
  AUTH_COOKIE_NAME,
  CUSTOMIZATION_FIELD_TYPES,
  ADDRESS_TYPES,
  DISCOUNT_TYPES,
  ORDER_STATUS,
  PAYMENT_STATUS,
  DELIVERY_TYPES,
  PAYMENT_PROVIDERS,
};
