const ROLES = {
  CUSTOMER: 'CUSTOMER',
  ADMIN: 'ADMIN',
};

const AUTH_COOKIE_NAME = 'access_token';

// How long checkout holds stock for an unpaid order before the sweep frees it.
const RESERVATION_TTL_MINUTES = 30;

const CUSTOMIZATION_FIELD_TYPES = {
  TEXT: 'TEXT',
  IMAGE: 'IMAGE',
  NUMBER: 'NUMBER',
  SELECT: 'SELECT',
  TEXTAREA: 'TEXTAREA',
};

const TAXONOMY_KINDS = {
  CATEGORY: 'CATEGORY',
  OCCASION: 'OCCASION',
};

// Pricing rules the storefront also displays. The server is authoritative; the
// client mirrors these only so the cart preview matches the charge.
const TAX_RATE = 0.18;
const FREE_SHIPPING_THRESHOLD = 1499;

const BANNER_PLACEMENTS = {
  HOME_HERO: 'HOME_HERO',
  HOME_PROMO: 'HOME_PROMO',
  PLP_TOP: 'PLP_TOP',
};

const ADDRESS_TYPES = {
  HOME: 'HOME',
  WORK: 'WORK',
  OTHER: 'OTHER',
};

const DISCOUNT_TYPES = {
  PERCENTAGE: 'PERCENTAGE',
  FLAT: 'FLAT',
};

const ORDER_STATUS = {
  PLACED: 'PLACED',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  PROCESSING: 'PROCESSING',
  CUSTOMIZATION: 'CUSTOMIZATION',
  READY_TO_SHIP: 'READY_TO_SHIP',
  SHIPPED: 'SHIPPED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
  FAILED: 'FAILED',
};

// Allowed destinations per status; anything absent is rejected.
const ORDER_STATUS_TRANSITIONS = {
  [ORDER_STATUS.PLACED]: [ORDER_STATUS.PAYMENT_CONFIRMED, ORDER_STATUS.CANCELLED, ORDER_STATUS.FAILED],
  [ORDER_STATUS.PAYMENT_CONFIRMED]: [
    ORDER_STATUS.PROCESSING,
    ORDER_STATUS.CUSTOMIZATION,
    ORDER_STATUS.CANCELLED,
    ORDER_STATUS.REFUNDED,
  ],
  [ORDER_STATUS.PROCESSING]: [
    ORDER_STATUS.CUSTOMIZATION,
    ORDER_STATUS.READY_TO_SHIP,
    ORDER_STATUS.CANCELLED,
    ORDER_STATUS.REFUNDED,
  ],
  [ORDER_STATUS.CUSTOMIZATION]: [ORDER_STATUS.READY_TO_SHIP, ORDER_STATUS.CANCELLED, ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.READY_TO_SHIP]: [ORDER_STATUS.SHIPPED, ORDER_STATUS.CANCELLED, ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.SHIPPED]: [ORDER_STATUS.OUT_FOR_DELIVERY, ORDER_STATUS.DELIVERED, ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.OUT_FOR_DELIVERY]: [ORDER_STATUS.DELIVERED, ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.DELIVERED]: [ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.CANCELLED]: [],
  [ORDER_STATUS.REFUNDED]: [],
  [ORDER_STATUS.FAILED]: [],
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  AUTHORIZED: 'AUTHORIZED',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

const DELIVERY_TYPES = {
  STANDARD: 'STANDARD',
  SAME_DAY: 'SAME_DAY',
  EXPRESS: 'EXPRESS',
  SCHEDULED: 'SCHEDULED',
};

const PAYMENT_PROVIDERS = {
  RAZORPAY: 'RAZORPAY',
};

module.exports = {
  ROLES,
  AUTH_COOKIE_NAME,
  RESERVATION_TTL_MINUTES,
  CUSTOMIZATION_FIELD_TYPES,
  TAXONOMY_KINDS,
  BANNER_PLACEMENTS,
  TAX_RATE,
  FREE_SHIPPING_THRESHOLD,
  ADDRESS_TYPES,
  DISCOUNT_TYPES,
  ORDER_STATUS,
  ORDER_STATUS_TRANSITIONS,
  PAYMENT_STATUS,
  DELIVERY_TYPES,
  PAYMENT_PROVIDERS,
};
